import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import { selecionarQuestoesAleatorias, embaralharOpcoesPergunta } from '../utils'

export default function Home() {
  const quantidadeQuestoes = 10;

  // console.log(selecionarQuestoesAleatorias(quantidadeQuestoes))

  const [perguntas, setPerguntas] = useState([]);
  const [perguntaAtual, setPerguntaAtual] = useState(0);
  const [respostaUsuario, setRespostaUsuario] = useState(null);

  useEffect(() => {
    console.log('ola')
    const perguntasSelecionadas = selecionarQuestoesAleatorias(quantidadeQuestoes);
    setPerguntas(perguntasSelecionadas.map(embaralharOpcoesPergunta))
  }, []);

  const handleCliqueResposta = (opcaoSelecionada) => {
    // Verificar se a opção selecionada está correta
    const estaCorreta = perguntas[perguntaAtual].respostaCorreta === opcaoSelecionada;

    // Definir a resposta do usuário e habilitar o botão "Próxima Pergunta"
    setRespostaUsuario(estaCorreta);
  };

  const handleProximaPergunta = () => {
    // Avançar para a próxima pergunta
    setPerguntaAtual(perguntaAtual + 1);
    // Limpar a resposta do usuário e desabilitar o botão "Próxima Pergunta"
    setRespostaUsuario(null);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Aplicativo de Quiz</h1>
        {perguntas.length > 0 && perguntaAtual < perguntas.length && (
          <div>
            <h2>{perguntas[perguntaAtual].pergunta}</h2>
            {perguntas[perguntaAtual].respostasErradas.map((opcao, index) => (
              <button
                key={index}
                onClick={() => handleCliqueResposta(opcao)}
                disabled={respostaUsuario !== null}
              >
                {opcao}
              </button>
            ))}
            <button onClick={handleProximaPergunta} disabled={respostaUsuario === null}>
              Próxima Pergunta
            </button>
          </div>
        )}
        {perguntaAtual === perguntas.length && (
          <p>Parabéns! Você concluiu o quiz.</p>
        )}
      </div>
    </>
  )
}
